# Generated by Django 5.1.2 on 2024-10-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('A', models.CharField(max_length=30)),
                ('B', models.CharField(max_length=30)),
                ('C', models.CharField(max_length=30)),
                ('D', models.CharField(max_length=30)),
                ('E', models.CharField(max_length=30)),
                ('F', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
