# Generated by Django 5.1.2 on 2024-10-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0002_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='B',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='C',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='D',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='E',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='F',
        ),
    ]
