# Generated by Django 5.1.2 on 2024-10-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0003_remove_answer_b_remove_answer_c_remove_answer_d_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='A',
            new_name='idq',
        ),
        migrations.AddField(
            model_name='answer',
            name='true_A',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
