# Generated by Django 5.1.2 on 2024-10-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0004_rename_a_answer_idq_answer_true_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='idq',
            field=models.IntegerField(max_length=30),
        ),
    ]
