# Generated by Django 5.1.2 on 2024-10-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0005_alter_answer_idq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='idq',
            field=models.CharField(max_length=30),
        ),
    ]
