# Generated by Django 5.1.2 on 2024-10-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0006_alter_answer_idq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='idq',
            new_name='i',
        ),
    ]
