# Generated by Django 5.1.2 on 2024-10-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0007_rename_idq_answer_i'),
    ]

    operations = [
        migrations.CreateModel(
            name='useraccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
            options={
                'db_table': 'useraccount',
            },
        ),
    ]
