# Generated by Django 5.1.2 on 2024-10-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0008_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='i',
            new_name='idq',
        ),
        migrations.AddField(
            model_name='answer',
            name='iduser',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
