# Generated by Django 5.1.2 on 2024-10-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0009_rename_i_answer_idq_answer_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
