# Generated by Django 5.1.2 on 2024-10-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0010_user_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='idq',
            new_name='concluson',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='true_A',
            new_name='noq',
        ),
        migrations.AddField(
            model_name='answer',
            name='true_Answer',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='user_Answer',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
