# Generated by Django 5.1.2 on 2024-11-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0012_remove_user_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='concluson',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='answer',
            name='iduser',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='answer',
            name='noq',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='answer',
            name='true_Answer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_Answer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='A',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='B',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='C',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='D',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='E',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='no',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
